spring:
  profiles:
    active: dev
    include: mvc
  resources:
    static-locations: classpath:static/,file:static/
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#   页面方面的配置
#  thymeleaf:
#    encoding: UTF-8
#    # 热部署静态文件
#    cache: false
#    # 让thymeleaf解析标签没有闭合时通过
#    mode: LEGACYHTML5

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.xld.core.entity

pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true