# 开发环境配置
server:
  port: 8081
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xld-project-case?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root

  #redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      # 最大连接数（负值表示没有限制）
      max-active: 8
      # 最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
      # 最大空闲链接
      max-idle: 8
      # 最小空闲链接
      min-idle: 0
    # 链接超时时间（毫秒）
    timeout: 0

fileUrlConfig:
  #文件访问根地址（外网访问）
  visitUrl: http://file.youbuxinxi.com/fileservice
  #文件操作根地址（文件服务器，内网访问）
  handleUrl: http://file.youbuxinxi.com/fileservice
  #文件服务器操作凭证
  token: ybxx@produceTest@20190409@1.0@iqmkj#kingtjmngff.04hlqmkj