spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:static/,file:static/
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.ybxx.core.entity

pagehelper:
  helperDialect: mysql